### ISSUE TITLE
ScanOptions.BACKGROUND not working with USB-3101FS

### ISSUE THREAD

**Issue by kevin-j-morse** [mccdaq/mcculw#15] opened 2019-07-18 19:51 UTC
I am using a USB-3101FS and copying the a_out_scan example.

I don't think the `ScanOptions.BACKGROUND` mode is working properly because after executing `ul.a_out_scan` there is a long pause and then "Waiting for output scan to complete..." appears immediately followed by "Scan completed successfully".

I am running Python 3.6.6 on Windows 10 64-bit

**Comment by jeffreyg3** [comment] 2019-07-18 20:29
Hi Kevin,
I just ran a_out_scan.py with a USB-3101FS on my Windows 7 64 bit computer, using Visual Studio 2015 with the python add in.  I do see a delay at the beginning of the app, but that is due to python taking time to generate the array of data.  
I put a break point on ul.a_out_scan() so it would run to that point and stop.  From the time I click start to the time it hits the break point there's a ~20 to 30 second delay.  When I click "continue" at ul.a_out_scan() my 'scope immediately starts to show the sine wave of channel 0 (what I'm monitoring).  and when the app states it is done, so is the data being output by the USB-3101FS.

**Comment by kevin-j-morse** [comment] 2019-07-18 20:41
Hi Jeff,

I also used breakpoints in the code as well as a print statement
immediately before and immediately after the call to ul.a_out_scan

What I see if is the "before" print statement executes, then analog output
starts immediately after (I'm watching it on a scope)

There is then a ten second period where the analog output is taking place
before I see the "after" print statement.

This runs counter to my understanding of the BACKGROUND option. My
understanding is that this option should allow the program to continue
executing after the analog output has started. This is not what I observe.

**Comment by kevin-j-morse** [comment] 2019-07-19 20:21
@jeffreyg3 I'm wondering if you have been able to reproduce this issue. I still can't get the BACKGROUND option to work for me...

**Comment by jeffreyg3** [comment] 2019-07-19 20:58
I have not been able to reproduce your issue.
How about this:
If you change the scan option from BACKGROUND to DEFAULTIO that will force foreground.

When you are in BACKGROUND, the next few lines of code (while loop) are run showing a message printed of

Waiting for output scan to complete...

while the loop runs, after every iteration it adds a "." to the end of the above.  
It can do this because it is in a loop checking the status of the background output scan calling ul.get_status(), looking for Status = IDLE.
 when the Status does equal IDLE, it exits the loop.  

This is a true background operation because the app continues immediately after the call to a_out_scan().  If it was foreground, the app would not be able to proceed to the next line until the output completes.

**Comment by kevin-j-morse** [comment] 2019-07-19 21:19
Hi @jeffreyg3 

I traced the problem to a difference between the Python 2 print function and the Python3 print function.

As written the `print("Waiting for output scan to complete...", end="")` followed by many `print(".", end="")` is buffered and does not show up until the final `print("")` is executed.

With Python3 the command needs to be `print("Waiting for output scan to complete...", end="", flush=True)` and the "." print statement should be `print(".", end="", flush=True)`

**Comment by kevin-j-morse** [comment] 2019-07-19 21:36
This stackexchange has more info https://stackoverflow.com/questions/493386/how-to-print-without-newline-or-space

I would suggest that if you want to make the code compatible with both Python 2 and 3 you should add a call to `sys.stdout.flush()` after both of the print statements. This is because the `__future__` version of the print function doesn't support the `flush=True` argument.

**Comment by jeffreyg3** [comment] 2019-07-22 14:54
Hi Kevin,
Thank you for your efforts in resolving this issue.  I have forwarded the information on to our developers for update in the next revision of the software.
Best regards,
Jeff

**Closed** 2019-07-22 15:28 UTC
